name: Build & Deploy image to GHCR

on:
  push:
    branches: ["main"]

jobs:
  build_and_publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/tiagocodecom/back-office:latest
          cache-from: type=registry,ref=ghcr.io/tiagocodecom/back-office:buildcache
          cache-to: type=registry,ref=ghcr.io/tiagocodecom/back-office:buildcache,mode=max